// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package echo

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OperationType int32

const (
	OperationType_INSERT OperationType = 0
	OperationType_DELETE OperationType = 1
)

var OperationType_name = map[int32]string{
	0: "INSERT",
	1: "DELETE",
}

var OperationType_value = map[string]int32{
	"INSERT": 0,
	"DELETE": 1,
}

func (x OperationType) String() string {
	return proto.EnumName(OperationType_name, int32(x))
}

func (OperationType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

type EchoRequest struct {
	Body                 string   `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EchoRequest) Reset()         { *m = EchoRequest{} }
func (m *EchoRequest) String() string { return proto.CompactTextString(m) }
func (*EchoRequest) ProtoMessage()    {}
func (*EchoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *EchoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EchoRequest.Unmarshal(m, b)
}
func (m *EchoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EchoRequest.Marshal(b, m, deterministic)
}
func (m *EchoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EchoRequest.Merge(m, src)
}
func (m *EchoRequest) XXX_Size() int {
	return xxx_messageInfo_EchoRequest.Size(m)
}
func (m *EchoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EchoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EchoRequest proto.InternalMessageInfo

func (m *EchoRequest) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type EchoReply struct {
	Body                 string   `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EchoReply) Reset()         { *m = EchoReply{} }
func (m *EchoReply) String() string { return proto.CompactTextString(m) }
func (*EchoReply) ProtoMessage()    {}
func (*EchoReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *EchoReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EchoReply.Unmarshal(m, b)
}
func (m *EchoReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EchoReply.Marshal(b, m, deterministic)
}
func (m *EchoReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EchoReply.Merge(m, src)
}
func (m *EchoReply) XXX_Size() int {
	return xxx_messageInfo_EchoReply.Size(m)
}
func (m *EchoReply) XXX_DiscardUnknown() {
	xxx_messageInfo_EchoReply.DiscardUnknown(m)
}

var xxx_messageInfo_EchoReply proto.InternalMessageInfo

func (m *EchoReply) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

// Wchar is W-character c
type Wchar struct {
	// Id is the id of c
	Id *Wid `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Visible is {true | false}, if the character c is visible
	Visible bool `protobuf:"varint,2,opt,name=visible,proto3" json:"visible,omitempty"`
	// Alpha is alphabetical value of the effective character of c
	CodePoint int32 `protobuf:"varint,3,opt,name=code_point,json=codePoint,proto3" json:"code_point,omitempty"`
	// PreviousId is the id of the previous W-character of c
	PreviousId *Wid `protobuf:"bytes,4,opt,name=previousId,proto3" json:"previousId,omitempty"`
	// NextId is the id of the next W-character of c
	NextId               *Wid     `protobuf:"bytes,5,opt,name=nextId,proto3" json:"nextId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Wchar) Reset()         { *m = Wchar{} }
func (m *Wchar) String() string { return proto.CompactTextString(m) }
func (*Wchar) ProtoMessage()    {}
func (*Wchar) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *Wchar) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Wchar.Unmarshal(m, b)
}
func (m *Wchar) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Wchar.Marshal(b, m, deterministic)
}
func (m *Wchar) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Wchar.Merge(m, src)
}
func (m *Wchar) XXX_Size() int {
	return xxx_messageInfo_Wchar.Size(m)
}
func (m *Wchar) XXX_DiscardUnknown() {
	xxx_messageInfo_Wchar.DiscardUnknown(m)
}

var xxx_messageInfo_Wchar proto.InternalMessageInfo

func (m *Wchar) GetId() *Wid {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Wchar) GetVisible() bool {
	if m != nil {
		return m.Visible
	}
	return false
}

func (m *Wchar) GetCodePoint() int32 {
	if m != nil {
		return m.CodePoint
	}
	return 0
}

func (m *Wchar) GetPreviousId() *Wid {
	if m != nil {
		return m.PreviousId
	}
	return nil
}

func (m *Wchar) GetNextId() *Wid {
	if m != nil {
		return m.NextId
	}
	return nil
}

// Wid is the id of W-character
type Wid struct {
	// The identifier of a site (a peer)
	Ns string `protobuf:"bytes,1,opt,name=ns,proto3" json:"ns,omitempty"`
	// The local clock of the W-character is generated on a site
	Ng                   int64    `protobuf:"varint,2,opt,name=ng,proto3" json:"ng,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Wid) Reset()         { *m = Wid{} }
func (m *Wid) String() string { return proto.CompactTextString(m) }
func (*Wid) ProtoMessage()    {}
func (*Wid) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *Wid) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Wid.Unmarshal(m, b)
}
func (m *Wid) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Wid.Marshal(b, m, deterministic)
}
func (m *Wid) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Wid.Merge(m, src)
}
func (m *Wid) XXX_Size() int {
	return xxx_messageInfo_Wid.Size(m)
}
func (m *Wid) XXX_DiscardUnknown() {
	xxx_messageInfo_Wid.DiscardUnknown(m)
}

var xxx_messageInfo_Wid proto.InternalMessageInfo

func (m *Wid) GetNs() string {
	if m != nil {
		return m.Ns
	}
	return ""
}

func (m *Wid) GetNg() int64 {
	if m != nil {
		return m.Ng
	}
	return 0
}

type Operation struct {
	Type                 OperationType `protobuf:"varint,1,opt,name=type,proto3,enum=echo.OperationType" json:"type,omitempty"`
	C                    *Wchar        `protobuf:"bytes,2,opt,name=c,proto3" json:"c,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Operation) Reset()         { *m = Operation{} }
func (m *Operation) String() string { return proto.CompactTextString(m) }
func (*Operation) ProtoMessage()    {}
func (*Operation) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}

func (m *Operation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Operation.Unmarshal(m, b)
}
func (m *Operation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Operation.Marshal(b, m, deterministic)
}
func (m *Operation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Operation.Merge(m, src)
}
func (m *Operation) XXX_Size() int {
	return xxx_messageInfo_Operation.Size(m)
}
func (m *Operation) XXX_DiscardUnknown() {
	xxx_messageInfo_Operation.DiscardUnknown(m)
}

var xxx_messageInfo_Operation proto.InternalMessageInfo

func (m *Operation) GetType() OperationType {
	if m != nil {
		return m.Type
	}
	return OperationType_INSERT
}

func (m *Operation) GetC() *Wchar {
	if m != nil {
		return m.C
	}
	return nil
}

func init() {
	proto.RegisterEnum("echo.OperationType", OperationType_name, OperationType_value)
	proto.RegisterType((*EchoRequest)(nil), "echo.EchoRequest")
	proto.RegisterType((*EchoReply)(nil), "echo.EchoReply")
	proto.RegisterType((*Wchar)(nil), "echo.Wchar")
	proto.RegisterType((*Wid)(nil), "echo.Wid")
	proto.RegisterType((*Operation)(nil), "echo.Operation")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 323 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xd1, 0x4e, 0xfa, 0x30,
	0x14, 0xc6, 0xe9, 0x18, 0xfc, 0xff, 0x3b, 0x8b, 0x88, 0xc7, 0x9b, 0x61, 0x62, 0x84, 0x25, 0x06,
	0x34, 0x86, 0x8b, 0xe9, 0x23, 0xb8, 0x0b, 0x12, 0x23, 0xa6, 0x92, 0xec, 0xd2, 0x40, 0xdb, 0x40,
	0x13, 0xd2, 0xd6, 0xad, 0x10, 0xf7, 0x48, 0xbe, 0xa5, 0x69, 0x41, 0x83, 0xc4, 0xbb, 0x73, 0xbe,
	0xef, 0xb7, 0xef, 0xac, 0xe7, 0x40, 0x34, 0x37, 0x72, 0x6c, 0x4a, 0x6d, 0x35, 0x86, 0x82, 0xad,
	0x74, 0x3a, 0x80, 0x38, 0x67, 0x2b, 0x4d, 0xc5, 0xfb, 0x46, 0x54, 0x16, 0x11, 0xc2, 0x85, 0xe6,
	0x75, 0x42, 0xfa, 0x64, 0x14, 0x51, 0x5f, 0xa7, 0x57, 0x10, 0xed, 0x10, 0xb3, 0xae, 0xff, 0x04,
	0x3e, 0x09, 0xb4, 0x0a, 0xb6, 0x9a, 0x97, 0xd8, 0x83, 0x40, 0x72, 0xef, 0xc5, 0x59, 0x34, 0x76,
	0x03, 0xc6, 0x85, 0xe4, 0x34, 0x90, 0x1c, 0x13, 0xf8, 0xb7, 0x95, 0x95, 0x5c, 0xac, 0x45, 0x12,
	0xf4, 0xc9, 0xe8, 0x3f, 0xfd, 0x6e, 0xf1, 0x12, 0x80, 0x69, 0x2e, 0xde, 0x8c, 0x96, 0xca, 0x26,
	0xcd, 0x3e, 0x19, 0xb5, 0x68, 0xe4, 0x94, 0x17, 0x27, 0xe0, 0x0d, 0x80, 0x29, 0xc5, 0x56, 0xea,
	0x4d, 0x35, 0xe1, 0x49, 0x78, 0x9c, 0x7d, 0x60, 0xe2, 0x00, 0xda, 0x4a, 0x7c, 0xd8, 0x09, 0x4f,
	0x5a, 0xc7, 0xd8, 0xde, 0x48, 0xaf, 0xa1, 0x59, 0x48, 0x8e, 0x1d, 0x08, 0x54, 0xb5, 0x7f, 0x44,
	0xa0, 0x2a, 0xdf, 0x2f, 0xfd, 0x8f, 0x35, 0x69, 0xa0, 0x96, 0xe9, 0x14, 0xa2, 0xa9, 0x11, 0xe5,
	0xdc, 0x4a, 0xad, 0x70, 0x08, 0xa1, 0xad, 0x8d, 0xf0, 0x78, 0x27, 0x3b, 0xdf, 0x85, 0xfe, 0xd8,
	0xb3, 0xda, 0x08, 0xea, 0x01, 0xec, 0x01, 0x61, 0x3e, 0x24, 0xce, 0xe2, 0xfd, 0x68, 0xb7, 0x16,
	0x4a, 0xd8, 0xed, 0x10, 0x4e, 0x7e, 0x7d, 0x81, 0x00, 0xed, 0xc9, 0xf3, 0x6b, 0x4e, 0x67, 0xdd,
	0x86, 0xab, 0x1f, 0xf3, 0xa7, 0x7c, 0x96, 0x77, 0x49, 0xf6, 0x00, 0x61, 0xa1, 0xb5, 0xc5, 0x3b,
	0x08, 0xdd, 0xd6, 0xf1, 0x6c, 0x17, 0x74, 0x70, 0xa4, 0x8b, 0xd3, 0x43, 0xc9, 0xac, 0xeb, 0xb4,
	0xb1, 0x68, 0xfb, 0x9b, 0xde, 0x7f, 0x05, 0x00, 0x00, 0xff, 0xff, 0x41, 0xa2, 0x35, 0x21, 0xe0,
	0x01, 0x00, 0x00,
}
